# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.36', '5.34' ]
        include:
          - perl: '5.38'
            os: ubuntu-latest
            release-test: true
            coverage: true
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: perl -V && cpanm -n Dist::Zilla && dzil authordeps --missing | cpanm -n --skip-satisfied && dzil listdeps --missing | grep -v tidied | cpanm -n --skip-satisfied
      - name: Run tests (no coverage)
        if: ${{ !matrix.coverage }}
        run: dzil test
      - name: Run tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dzil cover -test -report Coveralls
